version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0.4

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      # - orb-tools/lint:
      #     filters: *filters
      #     source_dir: orb
      - orb-tools/pack:
          filters: *filters
          source_dir: orb
      - orb-tools/review:
          filters: *filters
          source_dir: orb
          exclude: RC009,RC010
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          config_path: .circleci/continue.yml
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: vertex-orb
          requires: [orb-tools/lint, orb-tools/pack, orb-tools/review]
          filters: *filters
